//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelFusion.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExcelFusion.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compressing {0} ....
        /// </summary>
        internal static string Compressing {
            get {
                return ResourceManager.GetString("Compressing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not deserialize file &apos;{0}&apos;.
        /// </summary>
        internal static string CouldNotDeserialize {
            get {
                return ResourceManager.GetString("CouldNotDeserialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A path to a folder containing the structure of an Excel file..
        /// </summary>
        internal static string CreateArgumentDescription {
            get {
                return ResourceManager.GetString("CreateArgumentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates an Excel file based on a folder..
        /// </summary>
        internal static string CreateDescription {
            get {
                return ResourceManager.GetString("CreateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the Extension of the Excel file..
        /// </summary>
        internal static string CreateExtDescription {
            get {
                return ResourceManager.GetString("CreateExtDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the Excel file output..
        /// </summary>
        internal static string CreateOutDescription {
            get {
                return ResourceManager.GetString("CreateOutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracts files from an Excel file and/or integrates such files back into and Excel file..
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel closed..
        /// </summary>
        internal static string ExcelClosed {
            get {
                return ResourceManager.GetString("ExcelClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing Excel....
        /// </summary>
        internal static string ExcelClosing {
            get {
                return ResourceManager.GetString("ExcelClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel opened..
        /// </summary>
        internal static string ExcelOpen {
            get {
                return ResourceManager.GetString("ExcelOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening Excel....
        /// </summary>
        internal static string ExcelOpening {
            get {
                return ResourceManager.GetString("ExcelOpening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting {0} to &apos;{1}&apos; ....
        /// </summary>
        internal static string Extracing {
            get {
                return ResourceManager.GetString("Extracing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A path to an Excel file..
        /// </summary>
        internal static string ExtractArgumentDescription {
            get {
                return ResourceManager.GetString("ExtractArgumentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracts files from an Excel file..
        /// </summary>
        internal static string ExtractDescription {
            get {
                return ResourceManager.GetString("ExtractDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder where to extact the Excel file..
        /// </summary>
        internal static string ExtractOutDescription {
            get {
                return ResourceManager.GetString("ExtractOutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel file &apos;{0}&apos; not found..
        /// </summary>
        internal static string FileNotFoundMessage {
            get {
                return ResourceManager.GetString("FileNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder &apos;{0}&apos; not found..
        /// </summary>
        internal static string FolderNotFoundMessage {
            get {
                return ResourceManager.GetString("FolderNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, grant access to the Visual Basic Project..
        /// </summary>
        internal static string GrantAccess {
            get {
                return ResourceManager.GetString("GrantAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   ___            _ ___        _           
        /// | __|_ ____ ___| | __|  _ __(_)___ _ _   
        /// | _|\ \ / _/ -_) | _| || (_-&lt; / _ \ &apos; \  
        /// |___/_\_\__\___|_|_| \_,_/__/_\___/_||_| 
        ///==========================================
        ///Author: ByteForge 
        ///MIT License - 2024   .
        /// </summary>
        internal static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to it&apos;s a {0}. Exporting..
        /// </summary>
        internal static string ItsA {
            get {
                return ResourceManager.GetString("ItsA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the MIT license.
        /// </summary>
        internal static string LicenseDescription {
            get {
                return ResourceManager.GetString("LicenseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel could not run an AutoLoad macro..
        /// </summary>
        internal static string MacroError {
            get {
                return ResourceManager.GetString("MacroError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © 2024 ByteForge 
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy 
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal 
        ///in the Software without restriction, including without limitation the rights 
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell 
        ///copies of the Software, and to permit persons to whom the Software is 
        ///furnished to do so, subject to the following conditions: 
        ///
        ///The above copyright notice and thi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MitLicense {
            get {
                return ResourceManager.GetString("MitLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; Open..
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening &apos;{0}&apos;....
        /// </summary>
        internal static string Opening {
            get {
                return ResourceManager.GetString("Opening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output folder not specified..
        /// </summary>
        internal static string OutputFolderNotSpecified {
            get {
                return ResourceManager.GetString("OutputFolderNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing {0} ....
        /// </summary>
        internal static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference to {0} added to the project. GUID = &apos;{1}&apos;.
        /// </summary>
        internal static string ReferenceAdded {
            get {
                return ResourceManager.GetString("ReferenceAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add reference to {0}..
        /// </summary>
        internal static string ReferenceFailed {
            get {
                return ResourceManager.GetString("ReferenceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUID in reference to &apos;{0}&apos; in the project file differs from GUID in the VB project..
        /// </summary>
        internal static string ReferenceGuidError {
            get {
                return ResourceManager.GetString("ReferenceGuidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      in project file : {0}.
        /// </summary>
        internal static string ReferenceGuidProject {
            get {
                return ResourceManager.GetString("ReferenceGuidProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      in VB project   : {0}.
        /// </summary>
        internal static string ReferenceGuiVbProject {
            get {
                return ResourceManager.GetString("ReferenceGuiVbProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referece removed from VB proejct..
        /// </summary>
        internal static string ReferenceRemoved {
            get {
                return ResourceManager.GetString("ReferenceRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manipulates Excel files..
        /// </summary>
        internal static string RootCommandDescription {
            get {
                return ResourceManager.GetString("RootCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try again? Y/N.
        /// </summary>
        internal static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while compiling the VBA project..
        /// </summary>
        internal static string VbaCompileError {
            get {
                return ResourceManager.GetString("VbaCompileError", resourceCulture);
            }
        }
    }
}
